import type { Metadata, ResolvingMetadata } from 'next'import { Viewport } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export function generateViewport({ params }) {
  return {
width: "device-width",
    content: "viewport-fit=cover",
    initialScale: 1,  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
